services:
  postgres-library:
    image: postgres:17.4
    container_name: library
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
      POSTGRES_DB: library_db
    ports:
      - "5439:5432"
    volumes:
      - postgres-library-data:/var/lib/postgresql/data
    networks:
      - library-network

  library-production:
    container_name: libraryapi-production
    image: giordanni/libraryapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-library
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      CLIENT_ID: your_client_id
      CLIENT_SECRET: your_client_secret

    networks:
      - library-network

volumes:
  postgres-library-data:
networks:
  library-network: